use std::{
    collections::BTreeMap,
    fs,
    path::Path,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Manifest {
    pub(crate) name: String,
    pub(crate) version: String,
    pub(crate) entry: String,
    pub(crate) dependencies: BTreeMap<String, String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LockFile {
    pub(crate) name: String,
    pub(crate) version: String,
    pub(crate) packages: BTreeMap<String, String>,
}

impl Manifest {
    pub(crate) fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            version: "0.1.0".into(),
            entry: "main.nano".into(),
            dependencies: BTreeMap::new(),
        }
    }

    pub(crate) fn parse(source: &str) -> Result<Self, String> {
        let mut manifest = Manifest::new("nano-project");
        let mut section = String::new();

        for raw in source.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line.starts_with('[') && line.ends_with(']') {
                section = line[1..line.len() - 1].trim().to_string();
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                return Err(format!("Nano package: linha inválida '{line}'"));
            };
            let key = key.trim();
            let value = unquote(value.trim())?;

            match section.as_str() {
                "package" => match key {
                    "name" => manifest.name = value,
                    "version" => manifest.version = value,
                    "entry" => manifest.entry = value,
                    _ => return Err(format!("Nano package: chave desconhecida [package].{key}")),
                },
                "dependencies" => {
                    manifest.dependencies.insert(key.to_string(), value);
                }
                _ => return Err(format!("Nano package: seção desconhecida [{section}]")),
            }
        }

        validate_name(&manifest.name)?;
        if manifest.version.is_empty() {
            return Err("Nano package: version não pode ser vazia".into());
        }
        if manifest.entry.is_empty() {
            return Err("Nano package: entry não pode ser vazio".into());
        }
        Ok(manifest)
    }

    pub(crate) fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("[package]\n");
        out.push_str(&format!("name = \"{}\"\n", escape(&self.name)));
        out.push_str(&format!("version = \"{}\"\n", escape(&self.version)));
        out.push_str(&format!("entry = \"{}\"\n", escape(&self.entry)));

        if !self.dependencies.is_empty() {
            out.push_str("\n[dependencies]\n");
            for (name, path) in &self.dependencies {
                out.push_str(&format!("{name} = \"{}\"\n", escape(path)));
            }
        }

        out
    }

    pub(crate) fn load(root: &Path) -> Result<Self, String> {
        let path = root.join("Nano.toml");
        let source = fs::read_to_string(&path)
            .map_err(|e| format!("Nano package: não foi possível ler '{}': {e}", path.display()))?;
        Self::parse(&source)
    }
}

impl LockFile {
    pub(crate) fn from_manifest(manifest: &Manifest, root: &Path) -> Result<Self, String> {
        let mut packages = BTreeMap::new();
        packages.insert(manifest.name.clone(), root.to_string_lossy().into_owned());

        for (name, dependency) in &manifest.dependencies {
            let dep = Path::new(dependency);
            let resolved = if dep.is_absolute() {
                dep.to_path_buf()
            } else {
                root.join(dep)
            };
            let canonical = fs::canonicalize(&resolved)
                .map_err(|e| format!("Nano package: dependência '{name}' inválida '{}': {e}", resolved.display()))?;
            if !canonical.is_dir() {
                return Err(format!("Nano package: dependência '{name}' não é um diretório"));
            }
            packages.insert(name.clone(), canonical.to_string_lossy().into_owned());
        }

        Ok(Self {
            name: manifest.name.clone(),
            version: manifest.version.clone(),
            packages,
        })
    }

    pub(crate) fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is generated by Nano. Do not edit manually.\n\n");
        out.push_str("[package]\n");
        out.push_str(&format!("name = \"{}\"\n", escape(&self.name)));
        out.push_str(&format!("version = \"{}\"\n", escape(&self.version)));

        out.push_str("\n[packages]\n");
        for (name, path) in &self.packages {
            out.push_str(&format!("{name} = \"{}\"\n", escape(path)));
        }
        out
    }

    pub(crate) fn load(path: &Path) -> Result<Self, String> {
        let source = fs::read_to_string(path)
            .map_err(|e| format!("Nano package: não foi possível ler '{}': {e}", path.display()))?;
        let mut lock = LockFile {
            name: String::new(),
            version: String::new(),
            packages: BTreeMap::new(),
        };
        let mut section = String::new();

        for raw in source.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line.starts_with('[') && line.ends_with(']') {
                section = line[1..line.len() - 1].trim().to_string();
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                return Err(format!("Nano package: linha inválida no lock '{line}'"));
            };
            let value = unquote(value.trim())?;
            match section.as_str() {
                "package" if key.trim() == "name" => lock.name = value,
                "package" if key.trim() == "version" => lock.version = value,
                "packages" => {
                    lock.packages.insert(key.trim().to_string(), value);
                }
                _ => {}
            }
        }

        if lock.name.is_empty() {
            return Err("Nano package: lockfile sem package.name".into());
        }
        Ok(lock)
    }
}

pub(crate) fn init(root: &Path, name: &str) -> Result<(), String> {
    fs::create_dir_all(root)
        .map_err(|e| format!("Nano package: não foi possível criar '{}': {e}", root.display()))?;
    let manifest_path = root.join("Nano.toml");
    if manifest_path.exists() {
        return Err(format!("Nano package: '{}' já existe", manifest_path.display()));
    }

    let manifest = Manifest::new(name);
    fs::write(&manifest_path, manifest.render())
        .map_err(|e| format!("Nano package: não foi possível escrever '{}': {e}", manifest_path.display()))?;

    let main_path = root.join("main.nano");
    if !main_path.exists() {
        fs::write(&main_path, "function main() {\n    print \"Hello from Nano\"\n}\n")
            .map_err(|e| format!("Nano package: não foi possível criar '{}': {e}", main_path.display()))?;
    }
    Ok(())
}

pub(crate) fn add(root: &Path, name: &str, dependency: &str) -> Result<(), String> {
    validate_name(name)?;
    if dependency.trim().is_empty() {
        return Err("Nano package: dependência vazia".into());
    }
    let mut manifest = Manifest::load(root)?;
    manifest.dependencies.insert(name.to_string(), dependency.to_string());
    fs::write(root.join("Nano.toml"), manifest.render())
        .map_err(|e| format!("Nano package: não foi possível atualizar Nano.toml: {e}"))?;
    lock(root)
}

pub(crate) fn remove(root: &Path, name: &str) -> Result<(), String> {
    validate_name(name)?;
    let mut manifest = Manifest::load(root)?;
    if manifest.dependencies.remove(name).is_none() {
        return Err(format!("Nano package: dependência '{name}' não existe"));
    }
    fs::write(root.join("Nano.toml"), manifest.render())
        .map_err(|e| format!("Nano package: não foi possível atualizar Nano.toml: {e}"))?;
    lock(root)
}

pub(crate) fn lock(root: &Path) -> Result<(), String> {
    let manifest = Manifest::load(root)?;
    let lock = LockFile::from_manifest(&manifest, root)?;
    fs::write(root.join("Nano.lock"), lock.render())
        .map_err(|e| format!("Nano package: não foi possível escrever lockfile: {e}"))?;
    Ok(())
}

pub(crate) fn verify(root: &Path) -> Result<(), String> {
    let manifest = Manifest::load(root)?;
    let expected = LockFile::from_manifest(&manifest, root)?;
    let path = root.join("Nano.lock");
    let actual = LockFile::load(&path)?;

    if actual != expected {
        return Err("Nano package: Nano.lock não corresponde ao manifesto ou às dependências locais".into());
    }
    Ok(())
}

fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("Nano package: nome vazio".into());
    }
    if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-') {
        return Err(format!("Nano package: nome inválido '{name}'"));
    }
    Ok(())
}

fn unquote(value: &str) -> Result<String, String> {
    if value.len() >= 2 && value.starts_with('"') && value.ends_with('"') {
        Ok(value[1..value.len() - 1].replace("\\\"", "\"").replace("\\\\", "\\"))
    } else {
        Err(format!("Nano package: valor deve estar entre aspas: {value}"))
    }
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::{Manifest, LockFile};

    #[test]
    fn manifest_round_trip_is_deterministic() {
        let source = "[package]\nname = \"demo\"\nversion = \"1.2.3\"\nentry = \"src/main.nano\"\n\n[dependencies]\nbar = \"libs/bar\"\nfoo = \"libs/foo\"\n";
        let manifest = Manifest::parse(source).unwrap();
        assert_eq!(manifest.render(), source);
    }

    #[test]
    fn lockfile_is_sorted() {
        let manifest = Manifest::new("demo");
        let lock = LockFile::from_manifest(&manifest, std::path::Path::new(".")).unwrap();
        assert!(lock.render().contains("demo = \".\""));
    }

    #[test]
    fn dependency_add_and_remove_are_round_trippable() {
        let root = std::env::temp_dir().join(format!("nano-package-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        super::init(&root, "demo").unwrap();
        super::add(&root, "local", ".").unwrap();
        let loaded = Manifest::load(&root).unwrap();
        assert_eq!(loaded.dependencies.get("local").map(String::as_str), Some("."));
        super::remove(&root, "local").unwrap();
        let loaded = Manifest::load(&root).unwrap();
        assert!(!loaded.dependencies.contains_key("local"));
        let _ = std::fs::remove_dir_all(&root);
    }
}
